---
title: 异步解决方案
date: 2019-1-16 11:39:01
tag: JavaScript核心
category: JavaScript
---
## 解决异步的方案
- 高阶函数  函数是一等公民，函数可以当作参数，函数可以返回函数（偏函数，函数柯里化）callback

- Promise
- generator + co
- async + await

> 目标：写起来越来越像同步代码

### 高阶函数
需要批量产生一些方法：

```
function isType（type）{
    return function（content）{
        let t = Object.prototype.toString.call(content).replace(/\[object\s|\]/g,'');
        return t === type;
    }
}
let isString = isType('String');
isString('bac');
```

回调函数：

> 比如：执行一个函数  调用3次后 在执行另一个函数 ;
```
function after(times, callback){
    return function(){
        if(--times === 0){
            callback();
        }
    }
}
let eat = after(3, function(){
    console.log('eat');
});
eat();
eat();
eat(); // eat
```
> 比如：等待多个异步事件都返回后才执行某个函数，类似于Promise.all([])的功能。
```
function after(times, callback){
    let arr = [];
    return function(data){
        arr.push(data);
        if(times === arr.length){
            callback();
        }
    }
}
let eat = after(3, function(){
    console.log('eat');
});

然后在每个异步任务的回调里面执行eat();
```

### promise

注：这里我们再说一遍，**实际上 Promise#catch 只是 promise.then(undefined, onRejected); 方法的一个别名而已**。 也就是说，这个方法用来注册当promise对象状态变为Rejected时的回调函数。

 [Promise详解](http://liubin.org/promises-book/#promise-is-always-async)
 
 因此链式调用的最佳使用方法：
 - then里面只放入onFulfilled回调函数，失败的情况统一在catch里面处理。
 - 链式调用，且需要传值时，上一级onFulfilled函数要return一个promise或一个普通值，没有显式return的时候默认return undefined。
 - 如果上级then产生了异常，则后面的成功回调都不会执行。失败结果会到达catch或者then的reject回调。
 
 - 如果需要在then中置失败，不要用throw而是用Promise.reject();
 
 ```
 function taskA() {
    console.log("Task A");
}
function taskB() {
    console.log("Task B");
}
function onRejected(error) {
    console.log("Catch Error: A or B", error);
}
function finalTask() {
    console.log("Final Task");
}

var promise = Promise.resolve();
promise
    .then(taskA)
    .then(taskB)
    .catch(onRejected)
    .then(finalTask);
 ```
 ![promise-then-catch-flow.png](WEBRESOURCE2bb9286cba054ea3bca2a574fbe8896a)
 
 我们没有为 then 方法指定第二个参数(onRejected)，也可以像下面这样来理解。

`then`注册onFulfilled时的回调函数

`catch`注册onRejected时的回调函数

再看一下 上面的流程图 的话，我们会发现 Task A 和 Task B 都有指向 onRejected 的线出来。

这些线的意思是在 Task A 或 Task B 的处理中，在下面的情况下就会调用 onRejected 方法。

- 发生异常的时候

- 返回了一个Rejected状态的promise对象